<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />

    <!-- API -->
    <PackageVersion Include="Scalar.AspNetCore" Version="2.5.6" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />

    <!-- TESTS -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="Bogus" Version="35.6.5" />

    <!-- EF CORE -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />

    <!-- Identity -->
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />


    <!-- LOGS -->
    <PackageVersion Include="Serilog.Sinks.MongoDB" Version="7.2.0" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />

    <!-- SERVICE DEFAULTS -->
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.0.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.13.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.13.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.13.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.13.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.13.0" />
    <PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.Valkey" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.MongoDB" Version="13.0.0" />
  </ItemGroup>
</Project>