version: "3.8"

services:
  mongo-nexum-manager:
    image: mongo:latest
    container_name: mongo-nexum-manager
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  rabbitmq-nexum-manager:
    image: rabbitmq:3-management
    container_name: rabbitmq-nexum-manager
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
