<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6153885f-35b4-4791-ae68-30de4b2195c0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Api/Api.csproj" />
  </ItemGroup>

   <ItemGroup>
    <PackageReference Include="Aspire.Hosting.MongoDB" />
    <PackageReference Include="Aspire.Hosting.Valkey" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
</Project>
